zones:
  - polygon:
      - [110, 1064]
      - [624, 700]
      - [700, 700]
      - [309, 1064]
    color: ROBOFLOW

  - polygon:
      - [373, 1066]
      - [721, 700]
      - [800, 700]
      - [553, 1068]
    color: RED

  - polygon:
      - [615, 1071]
      - [816, 700]
      - [899, 700]
      - [820, 1071]
    color: BLUE

  - polygon:
      - [1067, 1058]
      - [1005, 700]
      - [1075, 700]
      - [1272, 1056]
    color: GREEN
  
  - polygon:
    - [1332, 1056]
    - [1112, 700]
    - [1185, 700]
    - [1524, 1054]
    color: YELLOW

  - polygon:
    - [1584, 1048]
    - [1226, 700]
    - [1322, 700]
    - [1806, 1056]
    color: WHITE

detection_model: "yolov8m.pt"  # Any ultralytics detection model. For example "yolov8n.pt", "yolov9m.pt", "yolo11n.pt".  | Find all available model in https://docs.ultralytics.com/models/
video_source:
  video_path: "VEHICLES_2"  # Path of video (mp4 or other format), or supervision asset name if 'is_supervision_asset' is set to True
  is_supervision_asset: True  # Set to 'True' if you want to use a supervision asset video. For example "VEHICLES", "SUBWAY", "BASKETBALL". | Find all available asset names in https://supervision.roboflow.com/latest/assets/#supervision.assets.list.VideoAssets